--Question 1
SELECT CATEGORIE, TYPE, COUNT(*) AS QUANTITE
FROM BIEN 
GROUP BY CATEGORIE, TYPE;

--Question 2
SELECT IDE, DESIGNATION
FROM ESPACE
START WITH IDE = 945
CONNECT BY PRIOR IDE = IDERATTACH;

--Question 3
SELECT NOM, PRENOM
FROM PROPRIO
WHERE IDP NOT IN (
    SELECT IDP 
    FROM BIEN 
    WHERE VILLE = 'Marseille'
);

--Question 4
SELECT VILLE, COUNT(*)
FROM BIEN
WHERE CATEGORIE = 'Maison de Ville'
GROUP BY VILLE
HAVING COUNT(*) > 10;


--Question 5
SELECT IDEBIEN, CATEGORIE, PRIX, (PRIX - (SELECT MIN(PRIX) FROM BIEN)) AS ECART_PRIX
FROM BIEN;

--Question 6
SELECT IDEBIEN, CATEGORIE, PRIX, 
(PRIX - (SELECT MIN(PRIX) FROM BIEN WHERE CATEGORIE = B.CATEGORIE)) AS ECART_PRIX
FROM BIEN B;

--Question 7
SELECT DISTINCT P.IDP, NOM, PRENOM
FROM PROPRIO P
JOIN BIEN B ON B.IDP = P.IDP
WHERE P.IDP IN ( 
    SELECT IDP
    FROM BIEN
    WHERE TYPE = 'Studio'
    GROUP BY IDP
    HAVING COUNT(*) >= 2
);

--Question 8
SELECT *
FROM PROPRIO P
WHERE NOT EXISTS(
    SELECT * 
    FROM BIEN B
    WHERE NOT EXISTS(
        SELECT * 
        FROM BIEN 
        WHERE P.IDP = BIEN.IDP
        AND B.CATEGORIE = BIEN.CATEGORIE
    )
);

--Question 9
SELECT IDE
FROM ESPACE
WHERE IDERATTACH IS NULL
START WITH DESIGNATION = 'Terrasse' AND SUPERFICIE = (
    SELECT MAX(Superficie)
    FROM ESPACE
    WHERE Designation = 'Terrasse'
)
CONNECT BY IDE = PRIOR IDERATTACH;

--Question 10
SELECT *
FROM PROPRIO P
WHERE NOT EXISTS(
    SELECT * 
    FROM BIEN B
    WHERE IDP = 105 
    AND NOT EXISTS(
        SELECT * 
        FROM BIEN 
        WHERE P.IDP = BIEN.IDP
        AND B.CATEGORIE = BIEN.CATEGORIE
    )
);

--Question 11
CREATE OR REPLACE VIEW PRIX_MINIMUM_CATEGORIE AS
SELECT CATEGORIE, MIN(PRIX) AS PRIX_MINIMUM
FROM BIEN
GROUP BY CATEGORIE;

SELECT B.IDEBIEN, B.CATEGORIE, B.PRIX, 
       (B.PRIX - P.PRIX_MINIMUM) AS ECART_PRIX
FROM BIEN B, PRIX_MINIMUM_CATEGORIE P
WHERE B.CATEGORIE = P.CATEGORIE;

SELECT IDP, VILLE, CATEGORIE, PRIX, TYPE
FROM BIEN
WHERE CATEGORIE = 'Maison de Ville';
